### ISSUE TITLE
Kicks me out a second after logging in

### ISSUE THREAD

**Issue by sven-borkert** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#116] opened 2022-06-21 06:16 UTC
Hi,

I'm using node 16.15 and Keycloak 18. I cloned this repo and and modified the issuer, client-id and scope (removed api) to adjust this demo to my Keycloak settings. 

I can log in successfully, it says I'm authenticated, have a valid token, it lists all the 3 tokens, etc. But After 1-2 seconds it reloads, switches to IsAuthenticated=false and everything is gone. This does not happen when I set sessionChecksEnabled to false in the config.

When it's in that state, clicking "force silent refresh" does not change it, but clicking "login" will get me logged in again without Keycloak showing the login dialog again, it still knows I'm logged in.

Last thing I see in Firefox network monitor is a GET to the auth endpoint like this:

GET https://localhost:8443/realms/myrealm/protocol/openid-connect/auth?response_type=code&client_id=democlient&state=R1VGWnBYaWRxWlExN0FJdC1QUTJKWWdjMmdGYlBIR20yTGwyN2Zvb2NFamZz&redirect_uri=http://localhost:4200/silent-refresh.html&scope=openid profile email&code_challenge=sssj46XZpZrcdps7FwCm4pzOwpHgiivB6u1jlNLGiaw&code_challenge_method=S256&nonce=R1VGWnBYaWRxWlExN0FJdC1QUTJKWWdjMmdGYlBIR20yTGwyN2Zvb2NFamZz&prompt=none

It gives an error in the redirect response:

location: http://localhost:4200/silent-refresh.html?error=login_required&state=R1VGWnBYaWRxWlExN0FJdC1QUTJKWWdjMmdGYlBIR20yTGwyN2Zvb2NFamZz

My Keycloak installation is pretty default, except for the added realm, client and user for testing. I would be grateful for any help with understanding why this happens. I have enabled full event logging in Keycloak, but this request returning the error does not even show up in the eventlog.

Regards,
Sven

**Comment by sven-borkert** [comment] 2022-06-21 07:33
Update/Solved:

This seems to be caused by uBlock Origin in my Firefox. I'll try to find out some more details about it.

**Comment by jeroenheijmans** [comment] 2022-06-21 18:39
Thanks for sharing the root cause, that might help others find this issue and a solution!

I'll close the issue but feel free to add any other details for others to find.

**Closed by jeroenheijmans** 2022-06-21 18:39 UTC
Labels: question

**Comment by sven-borkert** [comment] 2022-06-22 06:56
Hi,

I could not find out what uBlock Origin blocks exactly to break this mechanism, but it's easy reproducible that it does. It does not show anything blocked in the overview and the network request protocol.

I also noticed that enabling the "Enhanced Tacking Protection" in Firefox also breaks the silent refresh in the same way. 

It seems to me that this refresh mechanism with the hidden iframe is likely to be blocked by anti tracking tools, so this mechanism is not very safe to use as it might not work for many users? Do you have any opinion on that?

Regards,
Sven

**Comment by sven-borkert** [comment] 2022-06-22 06:58
(But lots of thanks for this nice sample application, it's very useful for learning and understanding :) )

**Comment by jeroenheijmans** [comment] 2022-06-22 20:34
Glad to hear the sample is useful!

The third party cookie blockades are certainly something that messes with the iframe-based silent refresh mechanism. You can read [my "SPA Necromancy"](https://infi.nl/nieuws/spa-necromancy/) blogpost for extensive details, or [a smaller version in the repo's readme](https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#-third-party-cookies).
